// Session actions
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// User actions
export const CURRENT_USER_SUCCESS = 'CURRENT_USER_SUCCESS';
export const ALL_USERS_REQUEST = 'ALL_USERS_REQUEST';
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS';
export const ALL_USERS_FAILURE = 'ALL_USERS_FAILURE';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

// Search actions
export const BOOK_SEARCH_REQUEST = 'BOOK_FORM_REQUEST';
export const BOOK_SEARCH_SUCCESS = 'BOOK_FORM_SUCCESS';
export const BOOK_SEARCH_UPDATE = 'BOOK_FORM_UPDATE';
export const BOOK_SEARCH_RESET = 'BOOK_FORM_RESET';

// Book actions
export const ADD_BOOK_REQUEST = 'ADD_BOOK_REQUEST';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE';
export const REMOVE_BOOK_REQUEST = 'REMOVE_BOOK_REQUEST';
export const REMOVE_BOOK_SUCCESS = 'REMOVE_BOOK_SUCCESS';
export const REMOVE_BOOK_FAILURE = 'REMOVE_BOOK_FAILURE';

// Rent actions
export const RENT_BOOK_REQUEST = 'RENT_BOOK_REQUEST';
export const RENT_BOOK_SUCCESS = 'RENT_BOOK_SUCCESS';
export const RENT_BOOK_FAILURE = 'RENT_BOOK_FAILURE';

// Return actions
export const RETURN_BOOK_REQUEST = 'RETURN_BOOK_REQUEST';
export const RETURN_BOOK_SUCCESS = 'RETURN_BOOK_SUCCESS';
export const RETURN_BOOK_FAILURE = 'RETURN_BOOK_FAILURE';

// Library action
export const LIBRARY_BOOKS_REQUEST = 'LIBRARY_BOOKS_REQUEST';
export const LIBRARY_BOOKS_SUCCESS = 'LIBRARY_BOOK_SUCCESS';
export const LIBRARY_BOOKS_FAILURE = 'LIBRARY_BOOK_FAILURE';
export const RENTED_BOOKS_REQUEST = 'RENTED_BOOKS_REQUEST';
export const RENTED_BOOKS_SUCCESS = 'RENTED_BOOKS_SUCCESS';
export const RENTED_BOOKS_FAILURE = 'RENTED_BOOKS_FAILURE';