// Session actions
export const LOG_IN_USER_PENDING = 'LOG_IN_USER_PENDING';
export const LOG_IN_USER_REJECTED = 'LOG_IN_USER_REJECTED';
export const LOG_IN_USER_FULFILLED = 'LOG_IN_USER_FULFILLED';
export const LOG_OUT_USER_FULFILLED = 'LOG_OUT_USER_FULFILLED';

// Form Change
export const UPDATE_FORM_NAME = 'UPDATE_FORM_NAME';
export const UPDATE_FORM_EMAIL = 'UPDATE_FORM_EMAIL';
export const UPDATE_FORM_PASSWORD = 'UPDATE_FORM_PASSWORD';