// User actions
export const CREATE_USERS_PENDING = 'CREATE_USERS_PENDING';
export const CREATE_USERS_REJECTED = 'CREATE_USERS_REJECTED';
export const CREATE_USERS_FULFILLED = 'CREATE_USERS_FULFILLED';

// Form Change
export const UPDATE_FORM_NAME = 'UPDATE_FORM_NAME';
export const UPDATE_FORM_EMAIL = 'UPDATE_FORM_EMAIL';
export const UPDATE_FORM_PASSWORD = 'UPDATE_FORM_PASSWORD';